#!/bin/sh

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

case "$(uname -s)" in

   Darwin)
     # echo 'Mac OS X'
	alias ls='ls -G'
     ;;

   Linux)
	alias ls='eza -a --color=always --group-directories-first'
	alias ll='eza -al --color=always --group-directories-first'
     ;;

   CYGWIN*|MINGW32*|MSYS*|MINGW*)
     # echo 'MS Windows'
     ;;
   *)
     # echo 'Other OS' 
     ;;
esac

# tmux aliases
alias tls="tmux list-sessions"
alias ta="tmux attach-session -t"
alias tk="tmux kill-session -t"

# neovim
alias nv="$ZDOTDIR/scripts/nv.sh"

# git
alias gs="git status"
alias ga="git add"
alias gaa="git add ."
alias gcm="git commit -m"
alias gca="git commit --amend"
alias gl="git log"
alias glo="git log --oneline"
alias glot="git log --oneline --graph --decorate"
alias gwa="git worktree add"
alias gwl="git worktree list"
alias gbl="git branch -avv"
alias gd="git diff"
alias gclean="git clean -i"
alias gpull="git pull"
alias gpush="git push origin HEAD:refs/for/$(git symbolic-ref --short HEAD)"

# lazygit
alias lg="lazygit"

# trashy
# alias tr="trash put"
# alias trl="trash list"
# alias trr="trash list | fzf --multi | awk '{$1=$1;print}' | rev | cut -d ' ' -f1 | rev | xargs trash restore --match=exact --force"

# wslview (part of WSL Utilities)
# opens files and directories in default Windows programs
if [[ -n "$WSL_DISTRO_NAME" ]]; then
    alias wv="wslview"      # Redundant if a link of /usr/bin/wslview is created at $HOME/.local/bin/wv 
    alias wmnt="sudo wslact auto-mount"
fi
