#!/bin/sh

# prompt customization guide:
# 1. https://www.youtube.com/watch?v=p4h-5B8k2NY
# 2. https://old.reddit.com/r/zsh/comments/cgbm24/multiline_prompt_the_missing_ingredient/

function set-prompt() {
  emulate -L zsh

  # UTF symbols:
  # 1. https://www.nerdfonts.com/cheat-sheet
  # 2. https://shapecatcher.com/

  # Prompt arrow ideas: ❯,, , , , , , , , , , ,󰘩 , , , , ,󰇛 ,󰵼 ,󰘧 ,󰽗 , , , , , , ,󰃚 ,󰃛 ,󰃜 ,󰞷 ,󱗼 ,󱗿 ,󰇘 ,󱗽 ,󱗾 ,󰇙 ,󰇜 ,󰇝 ,󰽤 ,󰤁 ,󰑂 󰑅 󰑀 ,󰐾 ,󰻂 , , , , , , , , 

  # Set the prompt

  # Style 1: Single pill
  # 19:23  2.141s  ~/dotfiles
  #  ls
  # PROMPT=$'\n'"%F{68}%f%K{68}%F{234}%D{%H:%M} %k%f%K{108}%F{234} ${LAST_CMD_DURATION} %k%f%K{131}%F{234} %2~%k%f%F{131}%f"$'\n'"%F{yellow} %f"

  # Style 2: Separate pills  
  # 19:32 998ms ~/dotfiles
  #  ls
  # PROMPT=$'\n'"%F{68}%f%K{68}%F{234}%D{%H:%M}%k%f%F{68}%f %F{108}%f%K{108}%F{234}${LAST_CMD_DURATION}%k%f%F{108}%f %F{131}%f%K{131}%F{234}%2~%k%f%F{131}%f"$'\n'"%F{yellow} %f"

  # Style 3: Single pill (like style 1)
  # PROMPT=$'\n'"%F{#2f4f4f}%f%K{#2f4f4f}%F{#f5deb3}%D{%H:%M}%f %F{#ffc0cb}|%f %F{#afeeee}${LAST_CMD_DURATION}%f %F{#ffc0cb}|%f %F{#adff2f}%2~%f%k%F{#2f4f4f}%f"$'\n'"%F{yellow} %f"
  PROMPT=$'\n'"%F{#2f4f4f}%f%K{#2f4f4f}%F{#40e0d0}%D{%H:%M}%f %F{#f0ffff}|%f %F{#adff2f}%2~%f%k%F{#2f4f4f}%f"$'\n'"%F{yellow} %f"

  # Set user input color
  # additional options: bold, underline, standout
  zle_highlight=( default:fg=226,bold )
}

precmd() {
  # if [[ -n $CMD_START_TIME ]]; then
  #   local end=$(date +%s.%N)
  #
  #   if [[ $CMD_START_TIME =~ '^[0-9]+\.[0-9]+$' && $end =~ '^[0-9]+\.[0-9]+$' ]]; then
  #     local duration=$(echo "$end - $CMD_START_TIME" | bc -l)
  #
  #     local formatted=""
  #     if (( $(echo "$duration < 1" | bc -l) )); then
  #       local ms=$(printf "%.0f" "$(echo "$duration * 1000" | bc -l)")
  #       formatted="${ms}ms"
  #     else
  #       formatted=$(printf "%.2fs" "$duration")
  #     fi
  #
  #     LAST_CMD_DURATION="${formatted}"
  #   else
  #     LAST_CMD_DURATION=""
  #   fi
  # else
  #   LAST_CMD_DURATION=""
  # fi

  # Apply the prompt
  set-prompt
}

preexec() {
  # CMD_START_TIME=$(date +%s.%N)
}

setopt no_prompt_{bang,subst} prompt_{cr,percent,sp}
autoload -Uz add-zsh-hook
add-zsh-hook precmd precmd
add-zsh-hook preexec preexec

