#!/bin/sh
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export LS_COLORS="ow=1;34"      # disable green highlights on directories on ls output

# Editor
export EDITOR="nvim"

# XDG Paths
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

# History
setopt APPEND_HISTORY
setopt SHARE_HISTORY
HISTFILE="$XDG_DATA_HOME"/zsh/history
SAVEHIST=100000
HISTSIZE=100000
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS

# Tmux config dir
export TMUXDOTDIR=$HOME/.config/tmux

# Setup Rust related env vars
if [ -f "$HOME/.cargo/env" ]; then
    . "$HOME/.cargo/env"
fi

# Cargo install dir
export CARGO_INSTALL_ROOT=$HOME/.local

# Windows user name and directory
if [[ -n "$WSL_DISTRO_NAME" ]]; then
    export WINUSERNAME=$(powershell.exe -c '$env:UserName' | tr -d '\r')
    export WINHOME="/mnt/c/Users/$WINUSERNAME"
fi

# Fzf
export FZF_DEFAULT_OPTS='--layout=reverse --border'

# Paths
export PATH="$HOME/.local/bin":$PATH
