#!/bin/zsh

# Function to source files if they exist
function zsh_add_file() {
    [ -f "$ZDOTDIR/$1" ] && source "$ZDOTDIR/$1"
}

### lf file manager ###
# Use lf to switch directories and bind it to ctrl-o
function lfcd() {
    tmp="$(mktemp -uq)"
    trap 'rm -f $tmp >/dev/null 2>&1 && trap - HUP INT QUIT TERM PWR EXIT' HUP INT QUIT TERM PWR EXIT
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
bindkey -s '^o' '^ulfcd\n'

### Windows File Explorer ###
# Command: wf directory_path
# - Opens windows file explorer at directory_path
# - Relative directory_path works
if [[ -n "$WSL_DISTRO_NAME" ]]; then
    function wf() {
        /mnt/c/Windows/explorer.exe $(wslpath -w "$1")
    }
fi

