#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export LS_COLORS="ow=1;34"      # disable green highlights on directories on ls output

# Editor
export EDITOR="nvim"

# XDG Paths
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

# Tmux config dir
export TMUXDOTDIR=$HOME/.config/tmux

# Cargo install dir
export CARGO_INSTALL_ROOT=$HOME/.local

# Windows user name and directory
if [[ -n "$WSL_DISTRO_NAME" ]]; then
    export WINUSERNAME=$(powershell.exe -c '$env:UserName' | tr -d '\r')
    export WINHOME="/mnt/c/Users/$WINUSERNAME"
fi

# Fzf
export FZF_DEFAULT_OPTS='--layout=reverse --border'

# Paths
export PATH="$HOME/.local/bin":$PATH
